spring:
  application:
    name: localstep

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
  config:
    import: optional:file:.env[.properties]

naver:
  maps:
    client-id: ${NAVER_MAPS_CLIENT_ID:dummy}
    client-secret: ${NAVER_MAPS_CLIENT_SECRET:dummy}

naverdev:
  client-id: ${NAVER_DEV_CLIENT_ID:dummy}
  client-secret: ${NAVER_DEV_CLIENT_SECRET:dummy}

jwt:
  secret: ${JWT_SECRET:your-very-secure-and-long-secret-key-1234567890}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
